create table ranks
(
    id          integer,
    discordid   text,
    username    text,
    bootyxp     integer,
    rank        text,
    datejoined  text,
    description text,
    birthday    text,
    country     text,
    swsxp       boolean
);
INSERT INTO public.ranks (id, discordid, username, bootyxp, rank, datejoined, description, birthday, country, swsxp) VALUES (null, '236510124070404097', 'Fitness Silvan', 215, 'Fitness Officer', '22.05.2021', 'Hi! 💯 I''m Silvan from Germany and 28 years old. I''m the original founder of the VRDancing discord server. Everything began when i first met the Fitness Marshall in PyPy''s Just Dance world. Since then i''ve been dancing for over a year now to him and the fun never stopped. I have improved physically as well as mentally massively and i want to bring this to other people as well. Welcome to the Cult! ', '', '', false);
INSERT INTO public.ranks (id, discordid, username, bootyxp, rank, datejoined, description, birthday, country, swsxp) VALUES (null, '180796908824952832', 'Chatmans', 205, 'Fitness Officer', '21.05.2021', 'Howdy, I''m Chatmans, I make the VRDancing world with mxmmix. A nerd from the very beginning, I would have never thought I''d dance and workout in my life. It made me meet so many wonderful people, I''m forever grateful. At this point I''m just glad I invested myself into this even if my hardware hate me for it.  Not a baguette speaker, don''t listen to the accent. Also I''m a cat.', '', '', false);
INSERT INTO public.ranks (id, discordid, username, bootyxp, rank, datejoined, description, birthday, country, swsxp) VALUES (null, '373880792918523904', 'MidnightEclipse', 140, 'Fitness Major', '21.05.2021', 'The FitnessGram PACER Test is a multistage aerobic capacity test that progressively gets more difficult as it continues.

The test is used to measure a student''s aerobic capacity as part of the FitnessGram assessment. Students run back and forth as many times as they can, each lap signaled by a beep sound. The test get progressively faster as it continues until the student reaches their max lap score.

The PACER Test score is combined in the FitnessGram software with scores for muscular strength, endurance, flexibility and body composition to determine whether a student is in the Healthy Fitness Zone™ or the Needs Improvement Zone.
The FitnessGram PACER Test is a multistage aerobic capacity test that progressively gets more difficult as it continues.

The test is used to measure a student''s aerobic capacity as part of the FitnessGram assessment. Students run back and forth as many times as they can, each lap signaled by a beep sound. The test get progressively faster as it continues until the student reaches their max lap score.

The PACER Test score is combined in the FitnessGram software with scores for muscular strength, endurance, flexibility and body composition to determine whether a student is in the Healthy Fitness Zone™ or the Needs Improvement Zone', '', '', false);
INSERT INTO public.ranks (id, discordid, username, bootyxp, rank, datejoined, description, birthday, country, swsxp) VALUES (null, '249639666100207617', 'Felky', 135, 'Fitness Major', '22.05.2021', 'ydfasdf', '', '', false);
INSERT INTO public.ranks (id, discordid, username, bootyxp, rank, datejoined, description, birthday, country, swsxp) VALUES (null, '234442172852731904', 'Scolly', 130, 'Fitness Major', '22.05.2021', 'I may dance at times, don''t know yet ', '', '', false);
INSERT INTO public.ranks (id, discordid, username, bootyxp, rank, datejoined, description, birthday, country, swsxp) VALUES (null, '163792067376447493', 'EZ', 130, 'Fitness Major', '22.05.2021', 'Your awesome custom description. (Change me with ''$setdesc'')', '', '', false);
INSERT INTO public.ranks (id, discordid, username, bootyxp, rank, datejoined, description, birthday, country, swsxp) VALUES (null, '693284052467187793', 'Kyōto', 125, 'Fitness Major', '22.05.2021', 'Your awesome custom description. (Change me with ''$setdesc'')', '', '', false);
INSERT INTO public.ranks (id, discordid, username, bootyxp, rank, datejoined, description, birthday, country, swsxp) VALUES (null, '490991194591985664', 'Dranenk', 115, 'Fitness Major', '22.05.2021', 'The fluffiest butt on the server. You should definitely check it out xD', '', '', false);
INSERT INTO public.ranks (id, discordid, username, bootyxp, rank, datejoined, description, birthday, country, swsxp) VALUES (null, '199540008095449089', 'Kohryu', 110, 'Fitness Major', '22.05.2021', 'If I would get one Euro of every Bio search of me I would have one Euro now...', '', '', false);
INSERT INTO public.ranks (id, discordid, username, bootyxp, rank, datejoined, description, birthday, country, swsxp) VALUES (null, '360086749525049356', 'Eizzi', 110, 'Fitness Major', '22.05.2021', 'I like to wiggle myself to the music.', '', '', false);
INSERT INTO public.ranks (id, discordid, username, bootyxp, rank, datejoined, description, birthday, country, swsxp) VALUES (null, '561561733915869194', 'Sakari`', 105, 'Fitness Major', '22.05.2021', 'Your awesome custom description. (Change me with ''$setdesc'')', '', '', false);
INSERT INTO public.ranks (id, discordid, username, bootyxp, rank, datejoined, description, birthday, country, swsxp) VALUES (null, '175389808191864832', 'Phoenix Star', 105, 'Fitness Major', '22.05.2021', 'Your awesome custom description. (Change me with ''$setdesc'')', '', '', false);
INSERT INTO public.ranks (id, discordid, username, bootyxp, rank, datejoined, description, birthday, country, swsxp) VALUES (null, '140176027124105217', 'Obaid', 105, 'Fitness Major', '22.05.2021', 'Your typical friendly guy who likes gaming, anime, and cars. I found out about dancing in vr when I was looking for something to do while standing still, because I get motion sickness very easily. And it instantly became one of my favourite hobbies', '', '', false);
INSERT INTO public.ranks (id, discordid, username, bootyxp, rank, datejoined, description, birthday, country, swsxp) VALUES (null, '241990094955872266', 'mxmmix', 105, 'Fitness Major', '21.05.2021', 'Started dancing in VRChat in November 2020 and quickly became addicted, found the VRDancing community and purchased FBT. I''m from the Netherlands and currently study Computer Science with an interest in VR, robotics and gamedev. I develop the VRDancing world together with Chatmans. Mainly, all the programming, UI and the database back-end. Feel free to ping me during the evenings when you feel like dancing and I might join! I''m transgender and use she/her pronouns :)', '', '', false);
INSERT INTO public.ranks (id, discordid, username, bootyxp, rank, datejoined, description, birthday, country, swsxp) VALUES (null, '813771862969417768', 'Alryca', 100, 'Fitness Major', '22.05.2021', 'Your awesome custom description. (Change me with ''$setdesc'')', '', '', false);
INSERT INTO public.ranks (id, discordid, username, bootyxp, rank, datejoined, description, birthday, country, swsxp) VALUES (null, '469085349705154570', 'Stiik', 100, 'Fitness Major', '22.05.2021', 'Your awesome custom description. (Change me with ''$setdesc'')', '', '', false);
INSERT INTO public.ranks (id, discordid, username, bootyxp, rank, datejoined, description, birthday, country, swsxp) VALUES (null, '241476877112442881', 'TinyShy', 95, 'Fitness Major', '22.05.2021', 'Your awesome custom description. (Change me with ''$setdesc'')', '', '', false);
INSERT INTO public.ranks (id, discordid, username, bootyxp, rank, datejoined, description, birthday, country, swsxp) VALUES (null, '92439575288352768', 'FatalZodiac', 90, 'Fitness Major', '22.05.2021', 'KINJAZ!?!?!?', '', '', false);
INSERT INTO public.ranks (id, discordid, username, bootyxp, rank, datejoined, description, birthday, country, swsxp) VALUES (null, '270272083219578881', 'icemaniak', 85, 'Fitness Major', '28.05.2021', 'Hi! I''m Icemaniak. A guy with a passion for dancing from the Netherlands. I''ve been dancing for 12 years now and I hope to add a few more before my body breaks of old age lmao. Beepboop I''m out', '', '', false);
INSERT INTO public.ranks (id, discordid, username, bootyxp, rank, datejoined, description, birthday, country, swsxp) VALUES (null, '177267412079476746', 'The Demon On Welfare', 85, 'Fitness Major', '22.05.2021', 'I am: me 💯 🔞 🚀👌 💯 ', '', '', false);
INSERT INTO public.ranks (id, discordid, username, bootyxp, rank, datejoined, description, birthday, country, swsxp) VALUES (null, '104977869205155840', 'Kanami', 85, 'Fitness Major', '22.05.2021', 'The guy that stained the dancefloor', '', '', false);
INSERT INTO public.ranks (id, discordid, username, bootyxp, rank, datejoined, description, birthday, country, swsxp) VALUES (null, '353157178187710465', 'Resistless', 85, 'Fitness Major', '22.05.2021', 'The opposite of Resistful', '', '', false);
INSERT INTO public.ranks (id, discordid, username, bootyxp, rank, datejoined, description, birthday, country, swsxp) VALUES (null, '157956957628530688', 'nyarip', 70, 'Fitness Rookie', '22.05.2021', 'I have 15600 hours on ffxiv and I can still deadlift both ur parents', '', '', false);
INSERT INTO public.ranks (id, discordid, username, bootyxp, rank, datejoined, description, birthday, country, swsxp) VALUES (null, '473404689891721226', 'revylee', 70, 'Fitness Rookie', '22.05.2021', 'Your awesome custom description. (Change me with ''$setdesc'')', '', '', false);
INSERT INTO public.ranks (id, discordid, username, bootyxp, rank, datejoined, description, birthday, country, swsxp) VALUES (null, '723217987774971975', '~Silentt~', 70, 'Fitness Rookie', '21.05.2021', 'I try to be a expressive dancer. More often derping about then anything tho.', '', '', false);
INSERT INTO public.ranks (id, discordid, username, bootyxp, rank, datejoined, description, birthday, country, swsxp) VALUES (null, '690196348833759289', 'RaeStar24', 65, 'Fitness Rookie', '21.05.2021', ' I guess you would call me Silvan''s waifu or the first lady of this cult, its nice to meet you! Lets move our bodies and have fun!', '', '', false);
INSERT INTO public.ranks (id, discordid, username, bootyxp, rank, datejoined, description, birthday, country, swsxp) VALUES (null, '439642739798310912', 'blizzflare', 65, 'Fitness Rookie', '27.05.2021', 'Your awesome custom description. (Change me with ''$setdesc'')', '', '', false);
INSERT INTO public.ranks (id, discordid, username, bootyxp, rank, datejoined, description, birthday, country, swsxp) VALUES (null, '283345537116143626', 'bp326', 60, 'Fitness Rookie', '22.05.2021', 'Your awesome custom description. (Change me with ''$setdesc'')', '', '', false);
INSERT INTO public.ranks (id, discordid, username, bootyxp, rank, datejoined, description, birthday, country, swsxp) VALUES (null, '220604247438393344', 'Cinte', 60, 'Fitness Rookie', '28.05.2021', 'aAAa', '', '', false);
INSERT INTO public.ranks (id, discordid, username, bootyxp, rank, datejoined, description, birthday, country, swsxp) VALUES (null, '453580398165884941', 'captaincat', 55, 'Fitness Rookie', '22.05.2021', 'Your awesome custom description. (Change me with ''$setdesc'')', '', '', false);
INSERT INTO public.ranks (id, discordid, username, bootyxp, rank, datejoined, description, birthday, country, swsxp) VALUES (null, '259993071922446337', 'gizmo888', 55, 'Fitness Rookie', '05.06.2021', 'Your awesome custom description. (Change me with ''$setdesc'')', '', '', false);
INSERT INTO public.ranks (id, discordid, username, bootyxp, rank, datejoined, description, birthday, country, swsxp) VALUES (null, '306496335345876992', 'Maunovaa', 50, 'Fitness Rookie', '22.05.2021', '! I can''t dance so i just wiggle to the music!', '', '', false);
INSERT INTO public.ranks (id, discordid, username, bootyxp, rank, datejoined, description, birthday, country, swsxp) VALUES (null, '212234798079410177', 'medlish', 50, 'Fitness Rookie', '22.05.2021', 'I totally do all these crazy moves with my legs, I just don''t have the trackers yet', '', '', false);
INSERT INTO public.ranks (id, discordid, username, bootyxp, rank, datejoined, description, birthday, country, swsxp) VALUES (null, '163860924417966080', 'Chocobò', 50, 'Fitness Rookie', '30.05.2021', 'Hi, I kidnap people.', '', '', false);
INSERT INTO public.ranks (id, discordid, username, bootyxp, rank, datejoined, description, birthday, country, swsxp) VALUES (null, '163685930891345921', 'Hell․', 45, 'Fitness Rookie', '23.05.2021', 'Your awesome custom description. (Change me with ''$setdesc'')', '', '', false);
INSERT INTO public.ranks (id, discordid, username, bootyxp, rank, datejoined, description, birthday, country, swsxp) VALUES (null, '321775427259596800', 'beniwolf', 45, 'Fitness Rookie', '30.05.2021', 'Your awesome custom description. (Change me with ''$setdesc'')', '', '', false);
INSERT INTO public.ranks (id, discordid, username, bootyxp, rank, datejoined, description, birthday, country, swsxp) VALUES (null, '208558614078554112', 'Rin boy', 45, 'Fitness Rookie', '06.06.2021', 'Your awesome custom description. (Change me with ''$setdesc'')', '', '', false);
INSERT INTO public.ranks (id, discordid, username, bootyxp, rank, datejoined, description, birthday, country, swsxp) VALUES (null, '197893826231271424', 'clearrainbow', 45, 'Fitness Rookie', '19.06.2021', 'Your awesome custom description. (Change me with ''$setdesc'')', '', '', false);
INSERT INTO public.ranks (id, discordid, username, bootyxp, rank, datejoined, description, birthday, country, swsxp) VALUES (null, '472916433303633920', 'めぐみネコ', 45, 'Fitness Rookie', '19.06.2021', 'Your awesome custom description. (Change me with ''$setdesc'')', '', '', false);
INSERT INTO public.ranks (id, discordid, username, bootyxp, rank, datejoined, description, birthday, country, swsxp) VALUES (null, '249821130637049858', 'GummiSammi', 40, 'Fitness Rookie', '22.05.2021', 'Your awesome custom description. (Change me with ''$setdesc'')', '', '', false);
INSERT INTO public.ranks (id, discordid, username, bootyxp, rank, datejoined, description, birthday, country, swsxp) VALUES (null, '422032098925477889', 'Laiskiainen', 35, 'Fitness Cadet', '06.06.2021', 'Your awesome custom description. (Change me with ''$setdesc'')', '', '', false);
INSERT INTO public.ranks (id, discordid, username, bootyxp, rank, datejoined, description, birthday, country, swsxp) VALUES (null, '271024593391714316', 'TheeSpankEngine', 30, 'Fitness Cadet', '22.05.2021', 'Your awesome custom description. (Change me with ''$setdesc'')', '', '', false);
INSERT INTO public.ranks (id, discordid, username, bootyxp, rank, datejoined, description, birthday, country, swsxp) VALUES (null, '637719829863989274', 'KingKalliath', 30, 'Fitness Cadet', '22.05.2021', 'Just ask if you want to know something <3', '', '', false);
INSERT INTO public.ranks (id, discordid, username, bootyxp, rank, datejoined, description, birthday, country, swsxp) VALUES (null, '306140479320227840', 'Demi Fox', 30, 'Fitness Cadet', '05.06.2021', 'Your awesome custom description. (Change me with ''$setdesc'')', '', '', false);
INSERT INTO public.ranks (id, discordid, username, bootyxp, rank, datejoined, description, birthday, country, swsxp) VALUES (null, '130686104864161792', 'Noa15Lv', 30, 'Fitness Cadet', '31.05.2021', 'Your awesome custom description. (Change me with ''$setdesc'')', '', '', false);
INSERT INTO public.ranks (id, discordid, username, bootyxp, rank, datejoined, description, birthday, country, swsxp) VALUES (null, '173591343371780096', 'TheNero', 30, 'Fitness Cadet', '12.06.2021', 'haha funny bird', '', '', false);
INSERT INTO public.ranks (id, discordid, username, bootyxp, rank, datejoined, description, birthday, country, swsxp) VALUES (null, '250486315160829952', 'Clockwork Angel', 30, 'Fitness Cadet', '12.06.2021', '“Don’t walk behind me, I may not lead.
Don’t walk in front of me, I may not follow.
Just walk beside me and be my friend.” -Albert Camus', '', '', false);
INSERT INTO public.ranks (id, discordid, username, bootyxp, rank, datejoined, description, birthday, country, swsxp) VALUES (null, '445513490493341697', 'Jaceyhd f752', 30, 'Fitness Cadet', '26.06.2021', 'Your awesome custom description. (Change me with ''$setdesc'')', '', '', false);
INSERT INTO public.ranks (id, discordid, username, bootyxp, rank, datejoined, description, birthday, country, swsxp) VALUES (null, '135691742937612288', 'Ayeton', 30, 'Fitness Cadet', '31.05.2021', 'Your awesome custom description. (Change me with ''$setdesc'')', '', '', false);
INSERT INTO public.ranks (id, discordid, username, bootyxp, rank, datejoined, description, birthday, country, swsxp) VALUES (null, '207833772211699714', 'Conniptions', 25, 'Fitness Cadet', '19.06.2021', 'Your awesome custom description. (Change me with ''$setdesc'')', '', '', false);
INSERT INTO public.ranks (id, discordid, username, bootyxp, rank, datejoined, description, birthday, country, swsxp) VALUES (null, '156424008202452992', 'kropsla', 20, 'Fitness Cadet', '30.05.2021', 'Hi, I am Raoul! I am a casual VR dancer that is also very much into Beat Saber and rhythm games of the likes. Besides being in VR, you can find me programming, bouldering, inline skating or being hungover. I aspire to speak to as many sweet Fitness Marshall enthousiasts as I can ❤️', '', '', false);
INSERT INTO public.ranks (id, discordid, username, bootyxp, rank, datejoined, description, birthday, country, swsxp) VALUES (null, '334745823701368832', 'Airstride#7689', 20, 'Fitness Cadet', '22.05.2021', 'Your awesome custom description. (Change me with ''$setdesc'')', '', '', false);
INSERT INTO public.ranks (id, discordid, username, bootyxp, rank, datejoined, description, birthday, country, swsxp) VALUES (null, '188804379845853184', 'Zargorth', 20, 'Fitness Cadet', '22.05.2021', 'I am 22 and am currently studying games development at university. I enjoy a large variety of games, anime and other shows and types of media. 
Nanachi is Best Nanachi is Life', '', '', false);
INSERT INTO public.ranks (id, discordid, username, bootyxp, rank, datejoined, description, birthday, country, swsxp) VALUES (null, '812347004352200724', 'Evelyno''', 20, 'Fitness Cadet', '25.05.2021', 'Your awesome custom description. (Change me with ''$setdesc'')', '', '', false);
INSERT INTO public.ranks (id, discordid, username, bootyxp, rank, datejoined, description, birthday, country, swsxp) VALUES (null, '110147170740494336', 'cakə', 20, 'Fitness Cadet', '22.05.2021', 'literal garbage with an icing exterior', '', '', false);
INSERT INTO public.ranks (id, discordid, username, bootyxp, rank, datejoined, description, birthday, country, swsxp) VALUES (null, '230005929817538561', 'Project_nep#1477', 20, 'Fitness Cadet', '22.05.2021', 'Your awesome custom description. (Change me with ''$setdesc'')', '', '', false);
INSERT INTO public.ranks (id, discordid, username, bootyxp, rank, datejoined, description, birthday, country, swsxp) VALUES (null, '238918198919954432', 'Yinagi', 20, 'Fitness Cadet', '30.05.2021', 'Your awesome custom description. (Change me with ''$setdesc'')', '', '', false);
INSERT INTO public.ranks (id, discordid, username, bootyxp, rank, datejoined, description, birthday, country, swsxp) VALUES (null, '332887282547687444', 'Akirathefrog#3058', 20, 'Fitness Cadet', '30.05.2021', 'Your awesome custom description. (Change me with ''$setdesc'')', '', '', false);
INSERT INTO public.ranks (id, discordid, username, bootyxp, rank, datejoined, description, birthday, country, swsxp) VALUES (null, '700155609693290576', 'Olivier#8941', 20, 'Fitness Cadet', '22.05.2021', 'Your awesome custom description. (Change me with ''$setdesc'')', '', '', false);
INSERT INTO public.ranks (id, discordid, username, bootyxp, rank, datejoined, description, birthday, country, swsxp) VALUES (null, '271987785471229952', 'KaKi_HolyMoly#1105', 20, 'Fitness Cadet', '09.06.2021', 'Your awesome custom description. (Change me with ''$setdesc'')', '', '', false);
INSERT INTO public.ranks (id, discordid, username, bootyxp, rank, datejoined, description, birthday, country, swsxp) VALUES (null, '739251688145289368', 'Kuuderekitten', 20, 'Fitness Cadet', '06.06.2021', 'Your awesome custom description. (Change me with ''$setdesc'')', '', '', false);
INSERT INTO public.ranks (id, discordid, username, bootyxp, rank, datejoined, description, birthday, country, swsxp) VALUES (null, '213814690101329920', '♛Maro♛', 20, 'Fitness Cadet', '12.06.2021', 'Your awesome custom description. (Change me with ''$setdesc'')', '', '', false);
INSERT INTO public.ranks (id, discordid, username, bootyxp, rank, datejoined, description, birthday, country, swsxp) VALUES (null, '259054010030489601', 'Mavor', 20, 'Fitness Cadet', '12.06.2021', 'Your awesome custom description. (Change me with ''$setdesc'')', '', '', false);
INSERT INTO public.ranks (id, discordid, username, bootyxp, rank, datejoined, description, birthday, country, swsxp) VALUES (null, '700113485744570369', 'Andyostr', 20, 'Fitness Cadet', '14.06.2021', 'Your awesome custom description. (Change me with ''$setdesc'')', '', '', false);
INSERT INTO public.ranks (id, discordid, username, bootyxp, rank, datejoined, description, birthday, country, swsxp) VALUES (null, '114100988427763714', 'therunningruski', 20, 'Fitness Cadet', '30.05.2021', 'Your awesome custom description. (Change me with ''$setdesc'')', '', '', false);
INSERT INTO public.ranks (id, discordid, username, bootyxp, rank, datejoined, description, birthday, country, swsxp) VALUES (null, '305765269756706818', 'mathqueen23', 20, 'Fitness Cadet', '14.06.2021', 'Your awesome custom description. (Change me with ''$setdesc'')', '', '', false);
INSERT INTO public.ranks (id, discordid, username, bootyxp, rank, datejoined, description, birthday, country, swsxp) VALUES (null, '166546576301359104', 'MiniGreen417', 20, 'Fitness Cadet', '22.05.2021', 'The Turnip Head', '', '', false);
INSERT INTO public.ranks (id, discordid, username, bootyxp, rank, datejoined, description, birthday, country, swsxp) VALUES (null, '140197385505603585', 'Remonite（レモナイト）', 20, 'Fitness Cadet', '19.06.2021', 'Your awesome custom description. (Change me with ''$setdesc'')', '', '', false);
INSERT INTO public.ranks (id, discordid, username, bootyxp, rank, datejoined, description, birthday, country, swsxp) VALUES (null, '345706926455259138', 'Mayodenayo', 20, 'Fitness Cadet', '12.06.2021', 'Your awesome custom description. (Change me with ''$setdesc'')', '', '', false);
INSERT INTO public.ranks (id, discordid, username, bootyxp, rank, datejoined, description, birthday, country, swsxp) VALUES (null, '282621039878471682', 'ITheShaxI', 15, 'Fitness Cadet', '26.06.2021', 'Your awesome custom description. (Change me with ''$setdesc'')', '', '', false);
INSERT INTO public.ranks (id, discordid, username, bootyxp, rank, datejoined, description, birthday, country, swsxp) VALUES (null, '801668735214551070', 'MinzLeaf', 15, 'Fitness Cadet', '26.06.2021', 'Your awesome custom description. (Change me with ''$setdesc'')', '', '', false);
INSERT INTO public.ranks (id, discordid, username, bootyxp, rank, datejoined, description, birthday, country, swsxp) VALUES (null, '252022895155347467', 'MrMoGumba', 15, 'Fitness Cadet', '26.06.2021', 'Your awesome custom description. (Change me with ''$setdesc'')', '', '', false);
INSERT INTO public.ranks (id, discordid, username, bootyxp, rank, datejoined, description, birthday, country, swsxp) VALUES (null, '267947247818375168', 'Pika#8270', 10, 'Fitness Cadet', '22.05.2021', 'Your awesome custom description. (Change me with ''$setdesc'')', '', '', false);
INSERT INTO public.ranks (id, discordid, username, bootyxp, rank, datejoined, description, birthday, country, swsxp) VALUES (null, '360500035873406989', 'Shaluna#7080', 10, 'Fitness Cadet', '22.05.2021', 'Your awesome custom description. (Change me with ''$setdesc'')', '', '', false);
INSERT INTO public.ranks (id, discordid, username, bootyxp, rank, datejoined, description, birthday, country, swsxp) VALUES (null, '387366580855767040', 'HolowVictory#5535', 10, 'Fitness Cadet', '22.05.2021', 'Your awesome custom description. (Change me with ''$setdesc'')', '', '', false);
INSERT INTO public.ranks (id, discordid, username, bootyxp, rank, datejoined, description, birthday, country, swsxp) VALUES (null, '202882373036015630', 'TheStrito#0909', 10, 'Fitness Cadet', '22.05.2021', 'Your awesome custom description. (Change me with ''$setdesc'')', '', '', false);
INSERT INTO public.ranks (id, discordid, username, bootyxp, rank, datejoined, description, birthday, country, swsxp) VALUES (null, '201969367083122688', 'deiffol', 10, 'Fitness Cadet', '22.05.2021', 'Your awesome custom description. (Change me with ''$setdesc'')', '', '', false);
INSERT INTO public.ranks (id, discordid, username, bootyxp, rank, datejoined, description, birthday, country, swsxp) VALUES (null, '225255429410783233', 'Zero-Kai#2510', 10, 'Fitness Cadet', '30.05.2021', 'Your awesome custom description. (Change me with ''$setdesc'')', '', '', false);
INSERT INTO public.ranks (id, discordid, username, bootyxp, rank, datejoined, description, birthday, country, swsxp) VALUES (null, '133765798408880128', 'Mana Moon#5008', 10, 'Fitness Cadet', '30.05.2021', 'Your awesome custom description. (Change me with ''$setdesc'')', '', '', false);
INSERT INTO public.ranks (id, discordid, username, bootyxp, rank, datejoined, description, birthday, country, swsxp) VALUES (null, '730963778514190439', 'nope_nope0', 10, 'Fitness Cadet', '30.05.2021', 'Your awesome custom description. (Change me with ''$setdesc'')', '', '', false);
INSERT INTO public.ranks (id, discordid, username, bootyxp, rank, datejoined, description, birthday, country, swsxp) VALUES (null, '315639448979111936', 'Starpo#4445', 10, 'Fitness Cadet', '30.05.2021', 'Your awesome custom description. (Change me with ''$setdesc'')', '', '', false);
INSERT INTO public.ranks (id, discordid, username, bootyxp, rank, datejoined, description, birthday, country, swsxp) VALUES (null, '390326170056523788', 'Kevin_ulti#0883', 10, 'Fitness Cadet', '30.05.2021', 'Your awesome custom description. (Change me with ''$setdesc'')', '', '', false);
INSERT INTO public.ranks (id, discordid, username, bootyxp, rank, datejoined, description, birthday, country, swsxp) VALUES (null, '642108178284412928', 'MikoTheFox#7883', 10, 'Fitness Cadet', '06.06.2021', 'Your awesome custom description. (Change me with ''$setdesc'')', '', '', false);
INSERT INTO public.ranks (id, discordid, username, bootyxp, rank, datejoined, description, birthday, country, swsxp) VALUES (null, '659129849285181440', 'Hani#4922', 10, 'Fitness Cadet', '12.06.2021', 'Your awesome custom description. (Change me with ''$setdesc'')', '', '', false);
INSERT INTO public.ranks (id, discordid, username, bootyxp, rank, datejoined, description, birthday, country, swsxp) VALUES (null, '327939763778879488', 'Tuntt', 10, 'Fitness Cadet', '12.06.2021', 'Your awesome custom description. (Change me with ''$setdesc'')', '', '', false);
INSERT INTO public.ranks (id, discordid, username, bootyxp, rank, datejoined, description, birthday, country, swsxp) VALUES (null, '403342004211154944', 'Yukii Shute#0311', 10, 'Fitness Cadet', '12.06.2021', 'Your awesome custom description. (Change me with ''$setdesc'')', '', '', false);
INSERT INTO public.ranks (id, discordid, username, bootyxp, rank, datejoined, description, birthday, country, swsxp) VALUES (null, '151763858778750978', 'Pendual''', 10, 'Fitness Cadet', '19.06.2021', 'Your awesome custom description. (Change me with ''$setdesc'')', '', '', false);
INSERT INTO public.ranks (id, discordid, username, bootyxp, rank, datejoined, description, birthday, country, swsxp) VALUES (null, '170205995941888000', 'Nayu~''', 10, 'Fitness Cadet', '19.06.2021', 'Your awesome custom description. (Change me with ''$setdesc'')', '', '', false);
INSERT INTO public.ranks (id, discordid, username, bootyxp, rank, datejoined, description, birthday, country, swsxp) VALUES (null, '240559887074066432', 'BBOSensei 0dce', 10, 'Fitness Cadet', '19.06.2021', 'Your awesome custom description. (Change me with ''$setdesc'')', '', '', false);
INSERT INTO public.ranks (id, discordid, username, bootyxp, rank, datejoined, description, birthday, country, swsxp) VALUES (null, '621028210213257236', '❤️Panda❤️', 10, 'Fitness Cadet', '02.06.2021', 'Your awesome custom description. (Change me with ''$setdesc'')', '', '', false);
INSERT INTO public.ranks (id, discordid, username, bootyxp, rank, datejoined, description, birthday, country, swsxp) VALUES (null, '155690667350163457', '｛Panda', 10, 'Fitness Cadet', '19.06.2021', 'Your awesome custom description. (Change me with ''$setdesc'')', '', '', false);
INSERT INTO public.ranks (id, discordid, username, bootyxp, rank, datejoined, description, birthday, country, swsxp) VALUES (null, '94485004641382400', 'a reb', 10, 'Fitness Cadet', '19.06.2021', 'Your awesome custom description. (Change me with ''$setdesc'')', '', '', false);
INSERT INTO public.ranks (id, discordid, username, bootyxp, rank, datejoined, description, birthday, country, swsxp) VALUES (null, '108414638323929088', '大神／オオガミ（kero）', 10, 'Fitness Cadet', '20.06.2021', 'Your awesome custom description. (Change me with ''$setdesc'')', '', '', false);
INSERT INTO public.ranks (id, discordid, username, bootyxp, rank, datejoined, description, birthday, country, swsxp) VALUES (null, '128227907293151232', 'Raindropss', 10, 'Fitness Cadet', '14.06.2021', 'Hi!~~', '', '', false);
INSERT INTO public.ranks (id, discordid, username, bootyxp, rank, datejoined, description, birthday, country, swsxp) VALUES (null, '313317856227885057', 'Beastcurry', 10, 'Fitness Cadet', '26.06.2021', 'Your awesome custom description. (Change me with ''$setdesc'')', '', '', false);
INSERT INTO public.ranks (id, discordid, username, bootyxp, rank, datejoined, description, birthday, country, swsxp) VALUES (null, '404692898496643075', 'Lizzyy00', 10, 'Fitness Cadet', '26.06.2021', 'Your awesome custom description. (Change me with ''$setdesc'')', '', '', false);
INSERT INTO public.ranks (id, discordid, username, bootyxp, rank, datejoined, description, birthday, country, swsxp) VALUES (null, '409998932853129216', 'konata#3131', 10, 'Fitness Cadet', '27.06.2021', 'Your awesome custom description. (Change me with ''$setdesc'')', '', '', false);
INSERT INTO public.ranks (id, discordid, username, bootyxp, rank, datejoined, description, birthday, country, swsxp) VALUES (null, '143407383236837386', 'SonicKitsune', 10, 'Fitness Cadet', '27.06.2021', 'I''m some guy/robot/something. Somehow I''m also into dancing.', '', '', false);
INSERT INTO public.ranks (id, discordid, username, bootyxp, rank, datejoined, description, birthday, country, swsxp) VALUES (null, '266027494463897624', 'Juno#9594', 10, 'Fitness Cadet', '14.06.2021', 'Your awesome custom description. (Change me with ''$setdesc'')', '', '', false);
INSERT INTO public.ranks (id, discordid, username, bootyxp, rank, datejoined, description, birthday, country, swsxp) VALUES (null, '201625791044386817', 'Burgerbeast', 0, 'Fitness Newcomer', '22.05.2021', 'Did someone say burgers?', '', '', false);
INSERT INTO public.ranks (id, discordid, username, bootyxp, rank, datejoined, description, birthday, country, swsxp) VALUES (null, '108162440658706432', 'spokeek#5623', 0, 'Fitness Newcomer', '22.05.2021', 'Your awesome custom description. (Change me with ''$setdesc'')', '', '', false);
INSERT INTO public.ranks (id, discordid, username, bootyxp, rank, datejoined, description, birthday, country, swsxp) VALUES (null, '467667173733826582', 'Shuta Shute#1100', 0, 'Fitness Newcomer', '22.05.2021', 'nutt', '', '', false);
INSERT INTO public.ranks (id, discordid, username, bootyxp, rank, datejoined, description, birthday, country, swsxp) VALUES (null, '719327982493106258', 'Coasterman98', 0, 'Fitness Newcomer', '22.05.2021', 'Your awesome custom description. (Change me with ''$setdesc'')', '', '', false);
INSERT INTO public.ranks (id, discordid, username, bootyxp, rank, datejoined, description, birthday, country, swsxp) VALUES (null, '246713306176421889', 'KarolPlayer', 0, 'Fitness Newcomer', '22.05.2021', 'Your awesome custom description. (Change me with ''$setdesc'')', '', '', false);
INSERT INTO public.ranks (id, discordid, username, bootyxp, rank, datejoined, description, birthday, country, swsxp) VALUES (null, '158878536873017344', 'SpleT', 0, 'Fitness Newcomer', '22.05.2021', 'Your awesome custom description. (Change me with ''$setdesc'')', '', '', false);
INSERT INTO public.ranks (id, discordid, username, bootyxp, rank, datejoined, description, birthday, country, swsxp) VALUES (null, '160225361001447424', 'kawffi', 0, 'Fitness Newcomer', '22.05.2021', 'Sleepy VR photographer that wants to get into dancing and drawing. Mute.', '', '', false);
INSERT INTO public.ranks (id, discordid, username, bootyxp, rank, datejoined, description, birthday, country, swsxp) VALUES (null, '318072796448161803', '-LAMIA-', 0, 'Fitness Newcomer', '22.05.2021', 'I''m like a credit card because I''m always being used or denied․', '', '', false);
INSERT INTO public.ranks (id, discordid, username, bootyxp, rank, datejoined, description, birthday, country, swsxp) VALUES (null, '235739619742842890', 'Dallezz', 0, 'Fitness Newcomer', '22.05.2021', 'Your awesome custom description. (Change me with ''$setdesc'')', '', '', false);
INSERT INTO public.ranks (id, discordid, username, bootyxp, rank, datejoined, description, birthday, country, swsxp) VALUES (null, '262713138753830913', 'Phoenix602', 0, 'Fitness Newcomer', '22.05.2021', 'Your awesome custom description. (Change me with ''$setdesc'')', '', '', false);
INSERT INTO public.ranks (id, discordid, username, bootyxp, rank, datejoined, description, birthday, country, swsxp) VALUES (null, '237016550027165697', 'Dragon_King', 0, 'Fitness Newcomer', '22.05.2021', 'Your awesome custom description. (Change me with ''$setdesc'')', '', '', false);
INSERT INTO public.ranks (id, discordid, username, bootyxp, rank, datejoined, description, birthday, country, swsxp) VALUES (null, '526694934212771840', 'Delicious Deli#9550', 0, 'Fitness Newcomer', '22.05.2021', 'Your awesome custom description. (Change me with ''$setdesc'')', '', '', false);
INSERT INTO public.ranks (id, discordid, username, bootyxp, rank, datejoined, description, birthday, country, swsxp) VALUES (null, '110276495825461248', 'Natsumi-sama', 0, 'Fitness Newcomer', '22.05.2021', 'Your awesome custom description. (Change me with ''$setdesc'')', '', '', false);
INSERT INTO public.ranks (id, discordid, username, bootyxp, rank, datejoined, description, birthday, country, swsxp) VALUES (null, '104391468793217024', 'GlueIsRequired#5243', 0, 'Fitness Newcomer', '05.06.2021', 'Your awesome custom description. (Change me with ''$setdesc'')', '', '', false);
INSERT INTO public.ranks (id, discordid, username, bootyxp, rank, datejoined, description, birthday, country, swsxp) VALUES (null, '206466673320919040', 'jayd!#0001', 0, 'Fitness Newcomer', '08.06.2021', 'hello!! em0catboy in vrc! !! dumb dancing femboy <3', '', '', false);
INSERT INTO public.ranks (id, discordid, username, bootyxp, rank, datejoined, description, birthday, country, swsxp) VALUES (null, '119377523409813504', 'LightShade#3876', 0, 'Fitness Newcomer', '11.06.2021', 'Your awesome custom description. (Change me with ''$setdesc'')', '', '', false);
INSERT INTO public.ranks (id, discordid, username, bootyxp, rank, datejoined, description, birthday, country, swsxp) VALUES (null, '243005076795293696', 'ZukiVR', 0, 'Fitness Newcomer', '13.06.2021', 'Your awesome custom description. (Change me with ''$setdesc'')', '', '', false);
INSERT INTO public.ranks (id, discordid, username, bootyxp, rank, datejoined, description, birthday, country, swsxp) VALUES (null, '162711463088095232', 'Towneh#0001', 0, 'Fitness Newcomer', '15.06.2021', 'Your awesome custom description. (Change me with ''$setdesc'')', '', '', false);
INSERT INTO public.ranks (id, discordid, username, bootyxp, rank, datejoined, description, birthday, country, swsxp) VALUES (null, '190167210872799233', 'TBG_VR', 0, 'Fitness Newcomer', '18.06.2021', 'Your awesome custom description. (Change me with ''$setdesc'')', '', '', false);
INSERT INTO public.ranks (id, discordid, username, bootyxp, rank, datejoined, description, birthday, country, swsxp) VALUES (null, '97021353672077312', 'Cinccino', 0, 'Fitness Newcomer', '19.06.2021', 'Your awesome custom description. (Change me with ''$setdesc'')', '', '', false);
INSERT INTO public.ranks (id, discordid, username, bootyxp, rank, datejoined, description, birthday, country, swsxp) VALUES (null, '151038791140900865', 'Poppy.', 0, 'Fitness Newcomer', '20.06.2021', 'Your awesome custom description. (Change me with ''$setdesc'')', '', '', false);
INSERT INTO public.ranks (id, discordid, username, bootyxp, rank, datejoined, description, birthday, country, swsxp) VALUES (null, '360478924519768078', 'BigSquishiePillows', 0, 'Fitness Newcomer', '22.06.2021', 'Just a lazy pillow trying to get some exercise to be less lazy!', '', '', false);
INSERT INTO public.ranks (id, discordid, username, bootyxp, rank, datejoined, description, birthday, country, swsxp) VALUES (null, '103575904080388096', 'vivikyu#0127', 0, 'Fitness Newcomer', '27.06.2021', 'Your awesome custom description. (Change me with ''$setdesc'')', '', '', false);
INSERT INTO public.ranks (id, discordid, username, bootyxp, rank, datejoined, description, birthday, country, swsxp) VALUES (null, '122485246905155584', 'Patroll#3959', 0, 'Fitness Newcomer', '28.06.2021', 'Your awesome custom description. (Change me with ''$setdesc'')', '', '', false);